### ISSUE TITLE
if 'PlayStation 5 Digital' in text or 'Playstation 5 Digital' in text:

### ISSUE THREAD

**Issue by oaigudmundsson** [ludvigbostrom/ps5kollen#3]
https://github.com/ludvigbostrom/ps5kollen/blob/c9a779523adbd63600722461807cf67ee3fe6bbd/pages.py#L65

Duplicate? Borde räcka med 

if 'PlayStation 5 Digital' in text:

Annars ser det bra ut! :)

**Comment by ludvigbostrom** [comment]
Fixat det
