### ISSUE TITLE
Verkar ge felaktig lagerstatus

### ISSUE THREAD

**Issue by nmbrg** [ludvigbostrom/ps5kollen#5]
Varit fyra mediamarkt uppdateringar och en inet uppdatering där det enligt scriptet ska vara i lager. Besökt sidorna inom sekunder från att den noterat och det har inte funnits något i lager.

var inga problem den noterade gångerna innan dessa och då har butikerna (dock andra butiker) haft i lager när den noterat om detta.

**Comment by nmbrg** [comment]
Det verkar som att den skriver ut att det är digital som finns i lager. Men det är standard som finns i lager när man tittar på mediamarkt. Hände idag precis igen.

**Comment by ludvigbostrom** [comment]
Problemet med mediamarkt är att de har många olika hanteringar av i lager/ej i lager men går beställa/ej i lager. De har också haft produkter där länkarna till en produkt gör en redirect till en annan liknande produkt. T.ex. konsol med 2 handkontroller skickas vidare till konsol med 1 handkontroll ibland. Därför är den inte exakt.

inet har jag inte själv upplevt att den missat. Men ibland är det bara i fysiska butiker.

 Kommer i dagsläget inte ändra något.
